# Generated by Django 6.0.5 on 2026-07-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(default='room_images/placeholder.jpg', upload_to='room_images/'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='image',
            field=models.ImageField(default='room_images/placeholder.jpg', upload_to='room_images/'),
        ),
    ]
