# Generated by Django 6.0.5 on 2026-09-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostels', '0005_hostelsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
    ]
