# Generated by Django 6.0.5 on 2026-09-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_booking_date_reservation_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='caretaker_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='mm_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='mm_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
