# Generated by Django 6.0.5 on 2026-09-04 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_reservation_caretaker_phone_reservation_mm_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='passport_photos/'),
        ),
    ]
