# Generated by Django 4.2.7 on 2026-06-23 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='student_id',
            new_name='student_reg_no',
        ),
    ]
